### ISSUE TITLE
You are violating the license agreement! 😡

### ISSUE THREAD

**Issue by andrey-helldar** [poseso/view-routes#1]
The source code of the Foo project is distributed under the MIT license, the terms of distribution of which are the obligatory indication of the author of the source code.

You took my code, created this repository, and replaced the copyright with yours. You can't do that.

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Solutions to the problem:
1. You need to recovery `Copyright (c) 2021 Andrey Helldar, Gary Green` in the [LICENCE](https://github.com/poseso/view-routes/blob/main/LICENSE#L3) file ([source license](https://github.com/andrey-helldar/pretty-routes/blob/main/LICENSE)) and [composer.json](https://github.com/poseso/view-routes/blob/main/composer.json#L7-L12) ([source composer.json](https://github.com/andrey-helldar/pretty-routes/blob/main/composer.json#L7-L16));
2. If you do not meet the first condition, then I am filing a complaint about the misuse of the code and you may be blocked on GitHub.

I give you a period of **10 days** - until **June 16, 2021**.

Source repository: https://github.com/andrey-helldar/pretty-routes

**Comment by poseso** [comment]
It wasn't mean to be like that, I will remove  this repo since it was meant to make tests, sorry for this, I understand it's yours sorry about that
